### ISSUE TITLE
Does this work Stripe and Redsys payment gateways? 

### ISSUE THREAD

**Issue by adrisantos07** [brainstormforce/edd-simple-after-payment-redirect#6]
I am hoping to use one of these payment gateways:
Redsys (http://modulosdepago.es/Redsys-easy-digital-downloads)
or Stripe .

Does this plugin work with them? If it doesn't I am willing to help integrating it.

Thanks very much for the plugin and regards.

**Comment by Nikschavan** [comment]
Hello @adrisantos07 We have not tested Redsys gateway and this plugin together. If you end up making any customizations do let us know and we can get your changes merged in the main plugin as well.
